sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test:ci
- npm run build:ci
before_deploy:
- cd dist/ngx-sdp
deploy:
  provider: npm
  email: erdikose8@gmail.com
  api_key:
    secure: kf2XmS60/ZOqONfoFbDJRbIUPP9oI/yCm9eol/ezMguzcOdvnyWAbsK9Pf5RrlEQPp3E+cR9Sdyt8+HFIrG9zdm1fJxYPxQFQDS0rczwi6xVQN9y6SRWZggnO0/CJ2buu5s8EbGvFOT1FYp+0MD1vc/7dbJAOlRjQa3Ty+3bKysDmKfH2dw34m2nOUGhpnpQXVmulhv+U043b0jWtJX+MdjDoo9sw0lz1dqhtiZEbzTstcQ9kbCMFAr/cqgy+54qnGeXJzGm/thfKuYpnJ8/l0EZ5EgL1GZFljlVR8rADl0EcSl34ZnG1/BIdtlr9A0rTYCvWs20wXcmlBWjZFIOqHyEZlK0ivQGhPqa4UMY54NSYtIT6iCUbkpLjW4nfZhLhpnoTdFT3w4UllrnHdY8SxDve2V8h7Q2g7/HR7HALqEphauEEzIfIzlh+d0mouitF7Fj/3bRXo8itgbQ1lm/3qhmtTezGPh5hYezWZQ/wrQXyWZSDm16dRv1EHMhX74OOGMAgL3BotB9Zb2rcmXKDO3c01j9Z/+8NVFd3TxMOt5gC+TYb0EuJ3WcFRkwOEzueGozDtfoh8lY8TQ0yD1ozda+g9tYNJC2xC1dvGfqA4d7msghHkcH1dWEqkkAANwUWMLesizpdXRLGI1yoRqwP0tCipQK2mBajpfwUK9wFI0=
  on:
    branch: master
    tags: true
    repo: erdkse/ngx-sdp
