sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test:ci
- npm run build:ci
before_deploy:
- npm install -g npm@'>=6'
- cd dist/ngx-sdp
deploy:
  provider: npm
  email: erdikose8@gmail.com
  api_key:
    secure: WsZcq/97rbyJmB+qd/RS5KvJdrXRaehwa7gXALZ6UYYugEAFTbhUQ6TjwGt6CAiv3Oz+BssfbEiBO1dTALoKFC37/OfO2RHsV89LLx25Foi4rzJtKPzWQMpcn5/Hai87yN2yT51uxLAC9oup+Ito5DOu3F+E9TvdLa1WgjLoHmXCYui00uKXoI28/+ANwJfwt/rmgTGjqIgd54dWaK6ITRzpNaJsv0HTwc+nioODDohJ3qY3XV1mTnjursj59MRnIPcLlD3uOpuigkOwpURPqkmdbPUH+IY2twNYcbPJNmiOftBe+ec7Q3OYtYweZILxWsadSnBcWOquH4CVLGQsURkwK95+LNVykDQT6lBfRWu/0J6CtKviCxyaQoTq8OWcmdVA3A5GvPHJN4t7fNwTNR18AufZ6MVOxv5X+r9Lw3WW63rHNLPNEEaSdu1tL2nBI5QVM7X9NY4LcEv2otgC3u5uoO5kpSv9WuCXxrBZCHPLlCFD7q1l5516GDRru8YMy72BCjd4blUZ90mKjuoanBH3ceWpxS/ldfsEiN5whVB5RfqwoOkIBkR28lK2p/6U9PNZUESRcXtayRuckM5VNDaFtGWwC4bPY/HU1F+6brmqefBbv8+M0YWEsLqMylNXlTtuGNioPOPc/ZvGT5bUK4LpWYnnr6HUbzlwfgthmS4=
  on:
    tags: true
    repo: erdkse/ngx-sdp
