sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test:ci
- npm run build:ci
before_deploy:
- npm install -g npm@'>=6'
- cd dist/ngx-sdp
deploy:
  provider: npm
  email: erdikose8@gmail.com
  api_key:
    secure: R7dfdTkvjacQ2JrAtTQX0l7wLI07ntsP/0bNk7HGMnQXHcjlQHm8KmYSS1lNIszGn1N+JJoLbHC0MdC5fQ4538fSYAem4+QHGjvjHDoKFODnaP+f74kk2dnuThPVRMzwAtxtDXJH8+5IPXPDhLSSLbF4r3B22bVeoj1lbvdXHyf3Js4v67OUQoXpbAEdexbOLBFm8mHwV2pmbkTEBW4jkI74m6I/LhedENXuHH/Y9hEBGFEqcy3xmXu1Kp6GJeN98Vm37neA/yysCXicaaqfHOSkEo1YfOhMKjuvO6OuS0FAnmXWNusnCazBuuIgoJKRSJm/IFTmgKoO8gSxCz4mT7yG4U7QRbe5LwD4Mpb5kyTYnRiKDQxeTa6inqvOOj468Olru1bBCGOtwWJiu8HU3eWs4rulnHYp8bjBKlowHGsgGUaeo/gt+ttD1ygvw9cnIjJzlQu6LpqzFEUMwcZ/ki4TqyMJPTzg5gB35AeAABBmnbDsRwDLGeIudQPIJJ7JyRF7/iuGKiYobdsvnZS1ft+a53957TT8Ez14sboyg5+JrEvyFuhB0yLTL07/VG/ZxAHt5B/epKmTVYpYQkBY7cC99P+GahylmzMF72OgVxURibovwXN9S5s0v0RJJfhOlDV7jsU+B15NXQnDRYgv/K6LYrt8N+4BKBVXFk/6jO0=
  on:
    tags: true
    repo: erdkse/ngx-sdp
    branch: master
